version: '3'
services:
  web:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "8000:80"
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  app:
    image: php:fpm-alpine
    volumes:
      - .:/var/www/html

